apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cs.name" . }}
  labels: {{- include "cs.labels" . | nindent 4 }}
  annotations: {{ .Values.serviceAccount.annotations | toJson }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cs.name" . }}-accounts
  labels: {{- include "cs.labels" . | nindent 4 }}
data:
  accounts.yaml: |
    accounts: {{ .Values.accounts | toJson }}
{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cs.secret" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.data.DATABASE_URL is required" .Values.secrets.data.DATABASE_URL | quote }}
  SECRET_KEY: {{ required "secrets.data.SECRET_KEY is required" .Values.secrets.data.SECRET_KEY | quote }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ required "secrets.data.POSTGRES_PASSWORD is required for Postgres" .Values.secrets.data.POSTGRES_PASSWORD | quote }}
  {{- end }}
  {{- range $key := list "AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "AWS_SESSION_TOKEN" "ALIBABA_CLOUD_ACCESS_KEY_ID" "ALIBABA_CLOUD_ACCESS_KEY_SECRET" }}
  {{- with index $.Values.secrets.data $key }}
  {{ $key }}: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
